config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/ordered'
  get 'customers/missing_email'
  root to: 'customers#index'
  resources :customers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence: true

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def ordered
    @ordered = Customer.all.order(:full_name)
  end

  def missing_email
    @missing_email_customers = Customer.where(email_address: '')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/commons/_menu.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        <%= link_to 'Home', customers_index_path%>
      </a>

      <a class="navbar-item">
        <%= link_to 'Ordered(Alphabetically)', customers_ordered_path%>
      </a>

      <a class="navbar-item">
        <%= link_to 'Missing Email List', customers_missing_email_path%>
      </a>

  </div>
</nav>

app/views/customers/_customer.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <% if customer.image.present? %>
        <div class="card-image">
          <figure class="image is-200x200">
            <%= image_tag(customer.image, size: "350x250")%>
          </figure>
        </div>
      <% end %>
      <p class="title">
        <%= link_to customer.full_name, customer %>
      </p>
      <p><%= customer.phone_number %> </p>
      <br/>
      <p><%= customer.email_address %> </p>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<h1 class="title is-2">All Customers</h1>


<%= render partial: 'customer', collection: @customers, locals:{ show_link: true } %>>

app/views/customers/missing_email.html.erb
<h1 class="title is-2">Customer's Missing Email</h1>


<%= render partial: 'customer', collection: @missing_email_customers, locals:{ show_link: true } %>

app/views/customers/ordered.html.erb
<h1 class="title is-2">Ordered</h1>


<%= render partial: 'customer', collection: @ordered, locals:{ show_link: true } %>>

app/views/customers/show.html.erb
<h1 class="title is-1"><%= @customer.full_name %></h1>

<div class="card">
    <div class="card-content">
      <% if @customer.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag @customer.image%>
          </figure>
        </div>
      <% end %>
      <p class="title">
        <%= @customer.full_name %>
      </p>
      <p><%= @customer.phone_number %> </p>
      <br/>
      <p><%= @customer.email_address %> </p>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CMSU6</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <h1 class="title is-1">U6</h1>

        <%= render partial: 'commons/menu' %>
        <%= yield %>

      </div>
    </section>
  </body>
</html>